OI-wiki/feedback-sys

frontend/lib/main.ts, frontend/lib/style.css
=> fix: #19, #20

cloudflare-workers/package.json, cloudflare-workers/src/administration.ts, cloudflare-workers/src/utils.ts, cloudflare-workers/yarn.lock
=> Enhancement Telegram Bot and bug fixes

frontend/lib/main.ts, frontend/lib/style.css
=> Feat: improve sending speed (fake)

.github/workflows/deploy-cloudflare-workers.yml, .github/workflows/publish-frontend.yml, .github/workflows/publish-python-markdown-extension.yml, python-markdown-extension/pyproject.toml
this pr also bump python-markdown-extension version to 0.3.0
=> CI: remove change stage

cloudflare-workers/src/db.ts
=> Refactor: postComment sql

cloudflare-workers/src/administration.ts, cloudflare-workers/src/index.ts, cloudflare-workers/src/types.ts
1. telegram bot name undefined
2. sql failed when github name not set
=> Fix: workers

cloudflare-workers/src/index.ts
https://oi-wiki.org/intro/mirrors/
fix #43
=> Feat: support mirror sites

frontend/lib/main.ts, frontend/lib/style.css
This PR makes the context menu floating, shows before paragraph. For mobile device, the menu will show on the top-center of the paragraph.
fix #18
=> Feat: floating review-context-menu

cloudflare-workers/src/administration.ts, cloudflare-workers/src/db.ts, cloudflare-workers/src/index.ts, cloudflare-workers/src/types.ts, cloudflare-workers/src/validation.ts, frontend/lib/main.ts, frontend/lib/style.css
=> Feat: modify && remove comment

cloudflare-workers/schema.sql, cloudflare-workers/src/db.ts, cloudflare-workers/src/types.ts, frontend/lib/main.ts, frontend/lib/style.css
=> feat: last edit time

cloudflare-workers/schema.sql, cloudflare-workers/src/db.ts, cloudflare-workers/src/index.ts, cloudflare-workers/src/types.ts, frontend/lib/main.ts, frontend/lib/style.css
此 PR 涉及表结构更改，合并前需要先重置表结构。
fix #56
=> Feat: user avatar

cloudflare-workers/src/index.ts, frontend/lib/main.ts, frontend/lib/style.css
=> Fix several bugs

frontend/lib/main.ts
=> fix: textarea autoheight not working

frontend/lib/style.css
=> fix(style.css): 将获取祖先修改为获取父亲

frontend/lib/main.ts, frontend/lib/style.css
=> refactor: use dataset instead of classlist

frontend/lib/main.ts, frontend/lib/style.css
=> perf: improve context menu performance

cloudflare-workers/package.json, frontend/package.json, python-markdown-extension/pyproject.toml
版本更新：
BTW，这里的流程应该是 merge 之后 打一下 tag 就 release 出去了？
cc @ZnPdCo
=> chore: bump to v0.5.2

cloudflare-workers/package.json, frontend/lib/main.ts, frontend/package.json, python-markdown-extension/pyproject.toml
fix #80
also bump feedback-sys version to 0.5.3
=> fix: querySelector npe

frontend/package.json
=> fix: npm publish warning

cloudflare-workers/schema.sql, cloudflare-workers/src/db.ts, cloudflare-workers/src/index.ts, cloudflare-workers/src/types.ts, frontend/lib/main.ts
fix #83 
此 PR 涉及表结构更改，需要修改表结构后才能合并
=> feat: jump to profile when click username

cloudflare-workers/package.json, frontend/package.json, python-markdown-extension/pyproject.toml
更新日志：
- 修复了中文用户名显示乱码的问题
- 修复了分享按钮权限控制错误的问题
- 更新了评论操作按钮的样式
=> chore: bump version to 0.5.5

.github/workflows/deploy-cloudflare-workers.yml, .github/workflows/publish-frontend.yml, .github/workflows/publish-python-markdown-extension.yml
upload-artifact@v2 has been deprecated seen the release of upload-artifact@v4, switch to v4 instead
=> fix: upload artifact

cloudflare-workers/src/db.ts
此 PR 修复了当用户重新登录时，其头像和用户 profile 未被更新的问题
=> fix: user data update

frontend/lib/style.css
=> style: 优化段落 hover 区域

cloudflare-workers/src/index.ts, cloudflare-workers/wrangler.toml
=> feat: add welcome screen on root

frontend/lib/dom/comment.ts, frontend/lib/dom/ctx_menu.ts
=> fix: fix focus fighting in textarea again

frontend/lib/style.css
=> fix: remove hover padding on mobile

cloudflare-workers/package.json, frontend/package.json, python-markdown-extension/pyproject.toml
更新日志：
1. 修复了pending状态没有被正确显示的问题
2. 修复了启用feedback sys时，手机上的正文宽度异常的问题
3. 给没有评论的页面添加了信息，并添加了 footer
=> chore: bump to v0.5.9

cloudflare-workers/package.json, frontend/package.json, python-markdown-extension/pyproject.toml
=> chore: bump to v0.5.10

frontend/lib/style.css
=> refactor: focused highlight

frontend/lib/dom/comment.ts, frontend/lib/style.css
=> feat: double confirm deletion

frontend/lib/dom/comment.ts
=> fix: actions buttion still available when pending

frontend/lib/dom/comment.ts
此 PR 修复了一个 bug，导致用户同时点击编辑和删除按钮时，二者的确认按钮同时出现
=> fix: race when click both modify and delete

cloudflare-workers/package.json, frontend/package.json, python-markdown-extension/pyproject.toml
更新记录：
- 改进选中和聚焦段落时的 UI 观感
- 删除评论时要求二次确认
- 网络请求窗口期禁止重复点击操作按钮
=> chore: bump to v0.5.11

frontend/lib/main.ts, frontend/lib/style.css
- Rounded and shadowed comment panel
- Muted footer text
Old
New
Old
New
By adding `review_dark_mode_class`
New (combined w/ Snipaste)
Old
New
Old
Emulated with devtool
New
Old
New
Old
Thx
=> Visual layering styling

cloudflare-workers/package.json, frontend/package.json, python-markdown-extension/pyproject.toml
更新记录：
- 改进部分 UI 元素的视觉观感
- 移动设备现在点击有评论的段落将不会打开评论面板（取而代之的，请主动点击添加评论按钮或侧边按钮来打开）
=> chore: bump to v0.5.12
